# Generated by Django 3.1.3 on 2020-11-11 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_num', models.IntegerField()),
                ('funding_date', models.DateField()),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_company', to='core.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_user', to='core.user')),
            ],
        ),
    ]
