# Generated by Django 3.1.3 on 2020-11-12 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_auto_20201112_0355'),
        ('forgiveness_request', '0002_auto_20201112_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgivenessrequest',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan', to='loan.loan', unique=True),
        ),
    ]
