# Generated by Django 3.1.3 on 2020-11-11 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(help_text='User email', max_length=254, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('address_one', models.CharField(blank=True, max_length=255, null=True)),
                ('address_two', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('zip', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_one', models.CharField(blank=True, max_length=255, null=True)),
                ('address_two', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('zip', models.CharField(blank=True, max_length=64, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('num_of_employees', models.IntegerField()),
                ('payroll_costs', models.DecimalField(decimal_places=2, max_digits=19)),
                ('business_mortgage_interest_payments', models.DecimalField(decimal_places=2, max_digits=19)),
                ('business_rent_or_lease_payments', models.DecimalField(decimal_places=2, max_digits=19)),
                ('business_utility_payments', models.DecimalField(decimal_places=2, max_digits=19)),
                ('sba_number', models.IntegerField()),
                ('ein', models.IntegerField()),
                ('dba', models.CharField(max_length=255)),
                ('entity_name', models.CharField(max_length=255)),
                ('primary_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_contact', to='core.user')),
            ],
        ),
    ]
