# Generated by Django 3.1.3 on 2020-11-11 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201111_2337'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('sba_number', 'ein'), ('ein',)},
        ),
    ]
