# Generated by Django 3.1.3 on 2020-11-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201111_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='wage_reductions_amount',
            field=models.IntegerField(default=0),
        ),
    ]
