# Generated by Django 3.1.3 on 2020-11-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_company_wage_reductions_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='reference_period',
            field=models.DateField(default='2020-01-01'),
            preserve_default=False,
        ),
    ]
